package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"
	"yol/graph/model"
)

// ReturnTime is the resolver for the ReturnTime field.
func (r *queryResolver) ReturnTime(ctx context.Context) (*model.ReturnTime, error) {
	str1 := "hi world"
	str2 := "oh hai world"
	str3 := "hello world"

	return &model.ReturnTime{
		UserService:       &str1,
		PostService:       &str2,
		ConnectionService: &str3,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
