// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type ReturnTime struct {
	UserService       *string `json:"user_service,omitempty"`
	PostService       *string `json:"post_service,omitempty"`
	ConnectionService *string `json:"connection_service,omitempty"`
}
